const constants = {
  TOGGLE_LOG_IN: 'TOGGLE_LOG_IN',
  LOG_IN_USER_SUCCESS: 'LOG_IN_USER_SUCCESS',
  TOGGLE_LOG_OUT: 'TOGGLE_LOG_OUT',
  LOG_OUT_USER: 'LOG_OUT_USER',
  TOGGLE_ADD_DOCUMENT: 'TOGGLE_ADD_DOCUMENT',
  FETCHED_DOCUMENTS: 'FETCHED_DOCUMENTS',
  FETCHED_TAGS: 'FETCHED_TAGS',
  SEARCH_DOCUMENTS: 'SEARCH_DOCUMENTS',
  FETCHED_PUBLIC_DOCUMENTS: 'FETCHED_PUBLIC_DOCUMENTS'
};

export default constants;

